// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejnyuuagcxomcqrcsajq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbnl1dWFnY3hvbWNxcmNzYWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTM0MzUsImV4cCI6MjA2MTA2OTQzNX0.GxxgqcfwgbIIwTbN0zW_4uhAQElwLXm111T3rljswPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);