
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// In a production environment, these would be environment variables
// For this project, we're storing them here directly since Lovable doesn't support .env files
const SUPABASE_URL = "https://ejnyuuagcxomcqrcsajq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbnl1dWFnY3hvbWNxcmNzYWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTM0MzUsImV4cCI6MjA2MTA2OTQzNX0.GxxgqcfwgbIIwTbN0zW_4uhAQElwLXm111T3rljswPc";

// Create a single instance of the Supabase client to use throughout the app
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions for common database operations
export const supabaseService = {
  // Auth related functions
  auth: {
    signUp: (email: string, password: string) => 
      supabase.auth.signUp({ email, password }),
    signIn: (email: string, password: string) => 
      supabase.auth.signInWithPassword({ email, password }),
    signOut: () => supabase.auth.signOut(),
    getSession: () => supabase.auth.getSession(),
    onAuthStateChange: (callback: any) => 
      supabase.auth.onAuthStateChange(callback)
  },
  // You can add more service methods as needed
};
